### ISSUE TITLE
S型规划最低要求

### ISSUE THREAD

**Issue by GoddessNaa** [FISHFISHFISHLOVECAT/OfflineScurveTrajectory#2]
在`bool ParaMinDisRequirement()`函数中，在达到最大加速度的情况下，`minq0q1 = 0.5 * (m_v0 + m_v1) * (Tjstar + fabs(m_v1 - m_v0) * m_amax);`是不是应该为`minq0q1 = 0.5 * (m_v0 + m_v1) * (Tjstar + fabs(m_v1 - m_v0) / m_amax);`
![image](https://user-images.githubusercontent.com/74918231/203686420-c76fa91b-66aa-4113-854a-47c916cb381f.png)

**Comment by simongeng1** [comment]
我觉得说的有道理，我也发现了这个问题

**Comment by liuminL** [comment]
的确应该是除

**Comment by FISHFISHFISHLOVECAT** [comment]
Fixed
