### ISSUE TITLE
Tv不存在时段

### ISSUE THREAD

**Issue by liuminL** [FISHFISHFISHLOVECAT/OfflineScurveTrajectory#3]
m_Tj1 = (m_jmax * (m_q1 - m_q0) - sqrt(m_jmax * (m_jmax * pow(m_q1 - m_q0, 2) + \
                pow(m_v1 + m_v0, 2) * (m_v1 - m_v0)))) / (m_jmax * (m_v1 + m_v0));

maybe :
m_Tj1 = (m_jmax * (m_q1 - m_q0) - sqrt(m_jmax * (m_jmax * pow(m_q1 - m_q0, 2) - \
                pow(m_v1 + m_v0, 2) * (m_v1 - m_v0)))) / (m_jmax * (m_v1 + m_v0));

**Comment by FISHFISHFISHLOVECAT** [comment]
Fixed
